version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .env
    networks:
      - network

  # clientapp:
  #   build: ./clientapp
  #   env_file: .env
  #   ports:
  #     - 5555:5555
  #   networks:
  #     - network
  #   volumes:
  #      - ./clientapp/src:/app/src
  #   depends_on:
  #     - rabbitmq

  sensorapp:
    build: ./sensorapp
    ports:
      - 6666:6666
    env_file: .env
    networks:
      - network
    volumes:
       - ./sensorapp/src:/app/src
    depends_on:
      - rabbitmq
      
  customerstreamapp:
    build: ./customerstreamapp
    ports:
      - 4444:4444
    env_file: .env
    networks: 
      - network
    depends_on:
      - rabbitmq

networks:
  network: {}
